// import { shimmer_card_unit } from "../constants";
import '../assets/stylesheet.css'
// Shimmer card to display with animation
const Shimmer = () => {
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap',  margin: '0 10px', gap: '15px'}}>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div> 
      <div style={{backgroundColor: '#f0f0f0', display: 'flex', flexDirection:'column', padding: '5px' , width: '20%', flexWrap: 'wrap', minHeight: '540px'}} className="shimmer-card"></div>
    </div>
  );
};

// const Shimmer = () => {
//   return (
//     <div className="shimmer-container">
//       {new Array(shimmer_card_unit).fill(0).map((element, index) => {
//         return <CardShimmer key={index} />;
//       })}
//     </div>
//   );
// };
export default Shimmer;